# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20190522_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
